package br.com.jcp.xyinc.ejb.entity;
//Generated Jan 20, 2015 4:54:18 PM by Hibernate Tools 3.4.0.CR1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * PointOfInterest generated by hbm2java
 */
@Entity
@Table(name="point_of_interest",catalog="xyincdb")
public class PointOfInterest  implements java.io.Serializable {

	private static final long serialVersionUID = -7153802638355637391L;
	
	private Long id;
	private String name;
	private int positionX;
	private int positionY;
	private Date createDate;

	public PointOfInterest() {
	}

	public PointOfInterest(String name, int positionX, int positionY, Date createDate) {
		this.name = name;
		this.positionX = positionX;
		this.positionY = positionY;
		this.createDate = createDate;
	}

	@Id @GeneratedValue(strategy=IDENTITY)
	@Column(name="id", unique=true, nullable=false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}


	@Column(name="name", nullable=false, length=100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	@Column(name="position_x", nullable=false)
	public int getPositionX() {
		return this.positionX;
	}

	public void setPositionX(int positionX) {
		this.positionX = positionX;
	}


	@Column(name="position_y", nullable=false)
	public int getPositionY() {
		return this.positionY;
	}

	public void setPositionY(int positionY) {
		this.positionY = positionY;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="create_date", nullable=false, length=19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Override
	public String toString() {
		return "PointOfInterest [id=" + id + ", name=" + name + ", positionX="
				+ positionX + ", positionY=" + positionY + ", createDate="
				+ createDate + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PointOfInterest other = (PointOfInterest) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
}